package com.kiran.musicapi.stockdata.api.contract;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;

import java.util.Map;

/** Immutable POJO representing the root response for the stock API. */
@Getter
@ToString
@EqualsAndHashCode
public final class StockApiResponse {
    private final Meta meta;
    private final Map<String, Quote> data;

    @JsonCreator
    public StockApiResponse(@JsonProperty("meta") Meta meta,
                            @JsonProperty("data") Map<String, Quote> data) {
        this.meta = meta;
        this.data = data == null ? null : java.util.Collections.unmodifiableMap(data);
    }

    // Getters, toString and equals/hashCode generated by Lombok
}
